spring:
  application:
    name: ALLCLEAR-was

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:default}
    username: ${DATABASE_USERNAME:default}
    password: ${DATABASE_PASSWORD:default}

